app:
  baseUrl: https://backstage.homelabdev.space

backend:
  baseUrl: https://backstage.homelabdev.space
  listen: ':7007'

catalog:
  locations:
    - type: file
      target: /app/catalog/org.yaml
      rules:
        - allow: [User, Group]
    - type: file
      target: /app/catalog/all.yaml
      rules:
        - allow: [Component, System, API, Resource, Location]
