version: '3.8'

services:
  gitea:
    image: gitea/gitea:1.25
    container_name: gitea
    restart: unless-stopped
    ports:
      - "3001:3000"
      - "2222:22"
    volumes:
      - /mnt/data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__ROOT_URL=https://gitea.homelabdev.space/
      - GITEA__server__SSH_DOMAIN=gitea.homelabdev.space
      - GITEA__server__PROTOCOL=http
      - GITEA__security__INSTALL_LOCK=true
      - GITEA__server__DISABLE_SSH=false
      - GITEA__server__SSH_PORT=2222
      - GITEA__server__HTTP_PORT=3000
      - GITEA__mailer__ENABLED=true
      - GITEA__mailer__PROTOCOL=smtp
      - GITEA__mailer__SMTP_ADDR=${SMTP_ADDR}
      - GITEA__mailer__SMTP_PORT=${SMTP_PORT}
      - GITEA__mailer__USER=${SMTP_USER}
      - GITEA__mailer__PASSWD=${SMTP_PASSWORD}
      - GITEA__mailer__FROM=${SMTP_FROM}
    networks:
      - default

networks:
  default:
    name: traefik_default
    external: true
